### ISSUE TITLE
Watchtower config arguments issue

### ISSUE THREAD

**Issue by mrKappa27** [F1DNA/FlexFarmerInDocker#1]
I notice that the actual Watchtower stack has an issue about a missing dash in the **cleanup** argument:
`command: --debug --interval 21600 –cleanup`
but even fixing with `--cleanup` doesn't solve the issue.

Both cases lead to this message ..."`Only checking containers with name \"–-cleanup\"`"...

I fixed the issue using this environment config:
```
environment:
      - TZ=Europe/Rome
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=21600
```

And now the message is: ..."`Checking all containers (except explicitly disabled with label)`"...

Hope this helps and If for you is ok I can open a PR.

Bye

**Comment by F1DNA** [comment]
Yes, thanks for catching that.  In my screenshot, you can see I have the double in there but either it pasted badly into the readme's code block or I accidentally deleted one during editing.  

Interesting that fixing that still resulted in the error for you as I see no issues in my log.  Putting it in as an environment variable is a fine solution.  Feel free to make a PR.

**Comment by F1DNA** [comment]
While you're at it, might as well move debug to the environment variable method as well:

WATCHTOWER_DEBUG=true

**Comment by F1DNA** [comment]
I went ahead and made the edits.  Thanks again for pointing that out.  Using environment variables is more in line with docker-compose than utilizing commands
